version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - postgres
    env_file:
      - ./.env

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_SSL: off
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./scripts/dbsetup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app


networks:
  app:
    driver: bridge 
